name: musict
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.2.6
  firebase_core: ^2.7.0
  firebase_auth: ^4.5.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.4.0
  image_picker: ^1.1.0
  url_launcher: ^6.0.20
  file_picker: ^5.2.2
  just_audio: ^0.9.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/kpop.jpg
    - assets/bigbang.jpg
    - assets/jj.jpg
    - assets/suho.jpg
    - assets/poo.jpg
    - assets/blackpink.jpg
    - assets/got7.jpg
    - assets/bts.jpg
    - assets/pop.jpg
    - assets/hiphop.jpg
    - assets/rock.jpg
    - assets/jazz.jpg
    - assets/album1.jpg
    - assets/album2.jpg
    - assets/album3.jpg
    - assets/album4.jpg
    - assets/album5.jpg
    - assets/album6.jpg
    - assets/love.jpg
    - assets/music.jpg
    - assets/mix.jpg
    - assets/sad.png
    - assets/love.png
    - assets/profile.jpg
